### ISSUE TITLE
Jjtree error

### ISSUE THREAD

**Issue by zeta9044** [javacc/javaccPlugin#62] opened 2023-01-31 06:21 UTC
plugins {
    id 'java-library'
    id "ca.coglinc.javacc" version "2.4.0"
}

compileJjtree {
    inputDirectory = file(parserDir)
    outputDirectory = file(parserDir)
    if (project.hasProperty("debug_parser")&&project.getProperty("debug_parser")!='') {
        arguments = [grammar_encoding: 'UTF-8',java_unicode_escape:'true',debug_parser:project.getProperty("debug_parser")]
    } else {
        arguments = [grammar_encoding: 'UTF-8',java_unicode_escape:'true',debug_parser:'false']
    }
}

2023-01-31T15:20:02.832+0900 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
Execution failed for task ':ShellParserV2:compileJjtree'.
> Unable to compile 'ShParser.jjt' from 'D:\git\lia-engine\ShellParserV2\src\com\ids\parser\Shell\sh' into 'D:\git\lia-engine\ShellParserV2\src\com\ids\parser\Shell\sh'

**Comment by zeta9044** [comment] 2023-01-31 06:23
javacc 'net.java.dev.javacc:javacc:4.0' error
but     javacc 'net.java.dev.javacc:javacc:4.1' well done

**Comment by zbynek** [comment] 2023-01-31 09:51
Duplicate of https://github.com/javacc/javaccPlugin/issues/50

**Closed by zbynek** 2023-01-31 09:51 UTC
